INSERT INTO department (name) VALUES ('Sony');
INSERT INTO department (name) VALUES ('MCU');
INSERT INTO role (title, salary, department_id) VALUES ('Spiderman', 0, 2);
INSERT INTO role (title, salary, department_id) VALUES ('Amazing Spiderman', 0, 1);
INSERT INTO role (title, salary, department_id) VALUES ('Wizard', 0, 2);
INSERT INTO role (title, salary, department_id) VALUES ('Person', 0, 2);
INSERT INTO employee (first_name,last_name, role_id) VALUES ('Peter', 'Parker', 1);
INSERT INTO employee (first_name,last_name, role_id) VALUES ('Michelle', 'Jones', 4);
INSERT INTO employee (first_name,last_name, role_id) VALUES ('Ned', '', 3);
INSERT INTO employee (first_name,last_name, role_id) VALUES ('Steven', 'Strange', 3);
